### ISSUE TITLE
Предложения по улучшению 2

### ISSUE THREAD

**Issue by seva-quijote** [Rocky-04/grade_converter_kinopoisk-IMDB#7]
Привет! Спасибо огромное за вашу работу – все ок, получилось выгрузить и загрузить на imdb (а отдельный файлик с ошибками – просто вау). У меня только 1 предложение и 1 пожелание:

1. Может, стоит на IMDB загружать фильмы в обратном порядке, чтобы сохранить тот же порядок, что и на кинопоиске? Сейчас загрузились в обратном (от старых оценок к новым), а заново делать уже неохота.
2. Очень хочется, чтобы можно было еще другие папки выгружать, а не только оценки. Самое актуальное – "Я буду смотреть".

**Comment by Rocky-04** [comment]
Здравствуйте! Рад, что все получилось!)
Спасибо за предложения, реализую.

**Comment by evil-pechenka** [comment]
Попробовал скачать — не получилось, Кинопоиск выдал капчу, потом ещё одну, после этого программа уходит в задумчивость навсегда.

И ещё мысль: [Кинориум](https://ru.kinorium.com/) позволяет выгрузить оценки из Кинопоиска — может дать возможность загружать их из файла на IMDB.

***

И всё так же не понятно зачем процесс скачивания оценок с Кинопоиска объединён с их загрузкой на IMDB, разделить было бы лучше, как мне кажется. Ну т.е. просто — выбрать файл и загрузить на IMDB.

**Comment by NikitaMesn** [comment]
Здравствуйте! Классная программа. Есть ли возможность выгрузить фильмы без оценок?
